### ISSUE TITLE
Introduce strict mode to fail on warnings

### ISSUE THREAD

**Issue by GaryGSC** [byu-oit/github-action-tf-plan-analyzer#80]
Something like
```yml
- name: Analyze Terraform Plan
  uses: byu-oit/github-action-tf-plan-analyzer@v2
  with:
    strict: true
```
or
```yml
with:
  fail-on-warning: true
```
